[mypy]
# Exclude the virtualenv and build directories from mypy checks
exclude = (?:^|/)(\.venv|build|dist|__pycache__)(?:/|$)

# Don't follow imports into third-party packages; prefer using local stubs
ignore_missing_imports = True

# Strictness flags
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
warn_return_any = True
warn_unused_ignores = True
show_error_codes = True

[mypy-optree.*]
ignore_errors = True

[mypy-torch.*]
ignore_missing_imports = True

[mypy-apex.*]
ignore_missing_imports = True
